language: python
python: '3.7'
before_install:
- sudo apt-get update
- sudo apt-get -y install libeigen3-dev
- sudo apt-get -y install libthrust-dev
- sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install twine wheel
script:
- pip install .
- pytest
deploy:
  provider: pypi
  distributions: sdist
  skip_existing: true
  user: carlidel
  password:
    secure: y/IaBpI9IFZEq26iQJcO6BYEtboYfJ473pX4sgPgNAA9sp7VJHRbt/5GONq/6Mny4W0U3yo/OAbjlR161CkpmMXBq/bYbaeJuvc7Fec7dS9C+itdkZWX7s0rcMn0SbKS1ha1kjyl2q2V/pxOHek3k4DLjpSTTx3QNIYOt/T/6nWqiZIoK6xh7zpmB0ylR/6XrBNceVl5i0BwMV2yahpbwNzwAQln15uCAqpYF/z7eQen+Kj443hQIV8ccdFlwD6r5VCebP6mvTUrKvn/Al4oBR27xe0C7CVboitj4Gkq31B62CGyoOo2Uywx7inHG/ziuxlC0z2yYGnTMDxNOCuDL2974TQbPUOuimb3fvAprQAwXKaO5SHbmJFkh1t1mduY/KabbCuK4K9zoADFr8qTO0tFfTqrfxul8Xh1iCdLcs7roqUC19w4sJrqlp34IGdwbAx3H3R3yENhsbxvmTG/6zbXitXCtAOULEjukGcEA02mtgbJ4fX3zPPYlKcvY0uvwxOmZ0pVcyhG2YoGRUizv0NoPJK8dh5XFNMrni9CLq0VBqCwL2grZ6RH9cW3ZGpR4r42ZAHoDw0G/buUtRMENSq2zu3JlYnhHXyunCKF9ym38qJqfkA3Gp1rnuathtQxWE+a9peXg2UcRmVTLyysfcyDbpr9A5+qQLhlpwtDWjs=
