language: python
python: '3.7'
before_install:
- sudo apt-get update
- sudo apt-get -y install libeigen3-dev
- sudo apt-get -y install libthrust-dev
- sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install twine wheel
script:
- pip install .
- pytest
deploy:
  provider: pypi
  distributions: sdist
  skip_existing: true
  user: carlidel
  password:
    secure: 6WrK1Vi7Kc54ns8yOscQ/UimFtkt4DcPjtaRjbAshM0IGLLPvqxtX+bKbjd8itcnn8ZWa4R6GHuLSZUdREh15YX7xcKJlz697Tc4rnK9DIAuKjFs084dGlI79Mr2ES3Wu/5lyI8HiL68jRm4huqDrtUVMIgvGhwEAmiSRHKCeyKioJdMwwCU2XNr9jztY0AwEKhiORHDWSA2wWgUQ9XWRg16p/lA1RQhtPP++hzxEzhOfjBxCBA5h4/F+xPBCr3G7BNnQBWUWKrLLW8yd92p5p6bHeH3eKYUJkv2fra3HvEXm9zEzFqu37F6wwTn97Jvg2ZDPDF1Ulsh5ZdFTv3w50smpYpaKxZxIuAdhnc1xitU4Ybl3J596ke9D9swj94rYHxI/4eUTdO47vf9hyHZmi2RXmmfqDD3vUOyn5Q2Coz6Sb2Ode4SeceK3mQ1mW6z60t1PisrE9/Zbm9IyPOZ7E3ieODAZlSvkuLu+QLYVcLl4FHcJ3hC8dr3UKWHskDHivhLZwSU4BntNSfOkH2Bt7jnMWgVLZTWw2ntZJlPh5rMIz59eS+MhEtK0cmxGsFqpoagj08rYKywUsKA3P2snaSu9EVub4fgrpGVt3tDqBHQTJ8ngcLe8/gM54MjITrj9qMFkf6CI5bsD1JEJEZ5rG8xClhV+beSiKkhnA9a0Rc=
