language: python
python: '3.7'
before_install:
- sudo apt-get update
- sudo apt-get -y install libeigen3-dev
- sudo apt-get -y install libthrust-dev
- sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install twine wheel
script:
- pip install .
- pytest
deploy:
  provider: pypi
  distributions: sdist
  skip_existing: true
  user: carlidel
  password:
    secure: qPHmgnxWQ9DY8NbvDf1idRysknaJbj9y5zfCXERo0LABTaJxCha/lLmMn5gm4Hi87IgE1ChVB3qDggGnvZ12oxeM6/JOelLrKW+15vRHzdS7jyBMDonKWh+DxdlRsTwwg74qGmgYILdjbGbrqb8NTltKEqZa9YtNgcjrRsfgAC36GWYnY+jHH1x5m77LL8xFXFC7JCLlDl61Ubd/5rByALINzLnQgGS5Y2a97Jj0CaZnPsTX+R6uRyhvNjdClPgCxol75XEn/K/slHkFblWsaEQ0fpJ2CwVp9QeLSOOK7b/ByWrDl3KfdzqlIl57HpX73nrwQ8qRaceegvQHmny4TVcYs5vdU/v5QZX98XuPeATYYzqc7PbkZrN7rGxlUiMP9mUkoeCWp2g3kPXuHCZ3PFEArG6rLgMM5sE23/gP08ThmgzxRST7aFHY3VP88uMKayBpDDGWT1Lt0px2dRx3f5J+KE3FxeAY5uz8D4GhgM3Y9UhyuyfadmfNpu1NTFRBo8yUsN91mRhqHnWLxz9YMUHgc3FEvJOX1/2VLD0XMEXToBN+gOjZgnbjZbltlEHRPqzXUtByWrNTbIoitb6FCd3LxKQq4QOq/kFyHGDD/9d8VBHwxIXVBDl57Xc8je5Fe2V5euoO2hr8assKuQbMmrdEXXlsgyG8HtLNCCnYCgw=
