language: python
python: '3.7'
before_install:
- sudo apt-get update
- sudo apt-get -y install libeigen3-dev
- sudo apt-get -y install libthrust-dev
- sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install twine wheel
script:
- pip install .
- pytest
deploy:
  provider: pypi
  distributions: sdist
  skip_existing: true
  user: carlidel
  password:
    secure: 1VrzUvvjthaqrFiHrq+Zfcg4wngs5IbLPq7kZzP5iOP58p4LAyQpFppGbw+YYWObmeqCai5C2Nbm5XlEINxC25Sk+Z0qg8EujVOg68Jd2Hx+u7BPSGoz+vdmpY9z8NGp2+8GJWdXeK3rOJuU0WIAx8Jd3yBlVMDwLh2fBIOts/5i9kI3YQGOo3C1OYn5b1UsCOFxN/nk4d3KYvnZlgUYY5OXnLIilDpePAXwlYzonVfwT3VsWqrb8J81RExooe9vmqzdHGNFyPLSVWBRWckqB7wt8Tv+lpeMM1BBDJAV0NVWxMbIYl+8OocGmaN1u3/mFPWGH9Y10f0iiDtcf5rKR9HLGUkxTPVKj5fBEwdHMHhF69xsRXGvH94Hb2BDeUNv9Ac74DyKeLfN8sRampsPQu3vrd7bt1F7BOgC5HI0qGjsWqR4PH/kVbkMPd6hEJfnnELAkJhtXY2MYsCGvnZAWHzDKVbma5RjLWM6sh5R1C90Zw3RzCbMQ3pq+f/xnEhqUeUt3mau6UTt6J8NwWm/PrQgwG0dNYOETE7UwftBUDLM3CMTyAH+CziP4dRmVwUpheGWCPX9HHKMLVwJyzV5ATQHbzbIYYFkB70FMJixL648q+dPE83+hl4CwrdOuCRd8gf8KFBnDSO5bpygkB9gf8CKVhDByq7k34roLUx8rkA=
